### ISSUE TITLE
Warning composer.json

### ISSUE THREAD

**Issue by jebog** [guillaumebriday/todolist-backend-laravel#26]
`Deprecation warning: Your package name larabackend is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.`

C'est pas très bloquant comme message mais tu devrais respecter le standard qui dit que le nom du package doit être sous la forme `guillaumebriday/todolist-backend-laravel`

Sinon Merci pour le Job.

**Comment by guillaumebriday** [comment]
Exact ! C'est corrigé dans ce commit : https://github.com/guillaumebriday/todolist-backend-laravel/commit/80fa49686b9ce8c989aa8c79c6c3623012783031

Merci à toi !
