### ISSUE TITLE
Cannot run php artisan migrate because of Mysql 8

### ISSUE THREAD

**Issue by kresnasatya** [guillaumebriday/todolist-backend-laravel#5]
Hi @guillaumebriday, thanks for providing this awesome feature. After I run `docker-compose run --rm todolist-server php artisan migrate`, it shows error like this picture:

![photo_2019-02-07 20 47 28](https://user-images.githubusercontent.com/11099186/52412421-b0173b00-2b19-11e9-878b-c35c6e9fb7ab.jpeg)

I suspect the problem is caching_sha2_password as mysql 8 authentication. How can you solve your problem about this one in your local computer?

**Comment by kresnasatya** [comment]
Hi there, because of nobody response, then I will close this issue.

**Comment by guillaumebriday** [comment]
Hey, sorry I didn't see your issue.

I didn't solve this issue so I'm still using mysql 5.7 for now. I know, it's not the best practice :/

cf: https://github.com/guillaumebriday/todolist-backend-laravel/commit/9d059b1a3a1e45f74d58102db8eb577afe9476a1

**Comment by kresnasatya** [comment]
Hi @guillaumebriday, thanks for the reply. Great, I will try again.

**Comment by connecteev** [comment]
php artisan migrate seems to work on Mysql v 8.0:
```
$ mysql --version
mysql  Ver 8.0.16 for osx10.13 on x86_64 (Homebrew)
```
